
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tvseries?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    username: root
    password: zhangliang0130
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd
    timezone: GMT+8
    serialization:
      write-dates-as-timestamps: false

logging:
  file: target/app.log
  level:
    ROOT: WARN
    demo.pkg.helloapp: TRACE
mybatis:
  configuration:
    map-underscore-to-camel-case: true
#mybatis-plus:
  #mybatisPlus mapper xml文件地址
  mapper-locations: classpath:/mapper/*.xml
  # mybaits-plus type-aliases 文件地址
  type-aliases-package: demo.pkg.helloapp.pojo
#  type-aliases-package: demo.pkg.helloapp.dao.TvSeriesDao

#此项目的自定义属性
tutorial:
  uploadFolder: target/upload-files/    #文件上传目录，可以用/开头的绝对路径